#!/bin/bash

# Path to the directory containing .webm files
input_dir="res/videos"

# Loop through each .webm file in the directory
for file in "$input_dir"/*.webm; do
    # Extract the filename without extension
    filename=$(basename "$file" .webm)
    # Convert the file to .mp4 with specified settings
    ffmpeg -i "$file" -r 60 -vf "fps=60,format=yuv420p" -c:v libx264 -preset veryfast -crf 0 -c:a copy "$input_dir/$filename.mp4"
done
